/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Color implements TEnum {
  RED(1),
  YELLOW(2),
  GREEN(3),
  BLUE(4);

  private final int value;

  private Color(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Color findByValue(int value) { 
    switch (value) {
      case 1:
        return RED;
      case 2:
        return YELLOW;
      case 3:
        return GREEN;
      case 4:
        return BLUE;
      default:
        return null;
    }
  }
}
